### ISSUE TITLE
ApplicationName parameter

### ISSUE THREAD

**Issue by testtwice** [sqlcollaborative/Invoke-SqlCmd2#15]
lines 386-389 have 
```powershell
if ($ApplicationName) {
    $CSBuilder["Application Name"] = $ApplicationName
}
```
but I don't see a parameter defined for $ApplicationName.

Should there be one like this?:

```powershell
[Parameter(Position = 11,
	Mandatory = $false,
	ValueFromPipelineByPropertyName = $true,
	ValueFromRemainingArguments = $false)]
[string]$ApplicationName
```

**Comment by alevyinroc** [comment]
Using the ConnectionStringBuilder was a change I started almost a year ago and things got muddy when I attempted to merge/PR my changes several months after I made the changes. I'll check into this, I probably missed something in copying my changes over.

**Comment by alevyinroc** [comment]
@potatoqualitee or @RamblingCookieMonster can you please assign this to me?
